name: CI Pipeline

on:
  - push

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v3
        with:
          node-version: 24.5.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm prettier . --check
      - name: Check linting
        run: pnpm run lint
  build:
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build Next.js pages
        run: pnpm run build
