name: PR Preview

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ./out
      - run: ls
      - run: ls out
