name: PR Preview

on:
  - pull_request

jobs:
  pre-build:
    uses: ./.github/workflows/ci.yml
  build:
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v3
        with:
          node-version: 24.5.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build Next.js pages
        run: pnpm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ./out
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: out
      - run: ls
      - run: ls out
